@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Setup  [self-unpacking]
rem  Generated by Venv Batch Template Generator (Leon Priest / 7h3v01d) v3.4.0
rem  Generated on: 2026-07-11 22:34
rem
rem  Ship ONLY this file in your repo.  On first run it:
rem    1. Checks Python
rem    2. Creates / verifies the virtual environment
rem    3. Installs dependencies
rem    4. Writes companion scripts beside this file:
rem       run.bat  pip.bat  shell.bat  sync.bat  doctor.bat  test.bat
rem
rem  Companion scripts are NOT overwritten if they already exist.
rem  Add them to .gitignore to keep your repo tidy.
rem ============================================================

set "PROJECT_NAME=Cryptkey"
set "VENV_DIR=.venv"

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setup: %PROJECT_NAME%
echo ============================================================
echo.

rem ── 1. Environment check + venv bootstrap ───────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Skipping creation.
    echo.
) else (
    echo [1/3] Creating virtual environment...
    echo ============================================================
    python -m venv "%VENV_DIR%"
    if errorlevel 1 ( echo [ERROR] venv creation failed. & pause & exit /b 1 )
    echo.

    echo [2/3] Upgrading pip...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo.

    if exist "requirements.txt" (
        echo [3/3] Installing dependencies from requirements.txt...
        echo ============================================================
        "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
        echo.
    ) else (
        echo [3/3] SKIPPED: No requirements.txt found.
        echo        Run sync.bat after adding dependencies.
        echo.
    )
)

rem ── 2. Write companion scripts ───────────────────────────────
echo ============================================================
echo  Writing companion scripts...
echo ============================================================
echo.

rem ── run.bat ─────────────────────────────────────────────────
set "OUTFILE=run.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_run_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbCBFbmFibGVEZWxheWVkRXhwYW5zaW9uDQpjZCAvZCAiJX5kcDAi
        echo DQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCBSdW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYg
        echo QmF0Y2ggVGVtcGxhdGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0K
        echo cmVtICBHZW5lcmF0ZWQgb246IDIwMjYtMDctMTEgMjI6MzQNCnJlbQ0KcmVtICBFTlRSWV9NT0RF
        echo Og0KcmVtICAgIGZpbGUgICAtPiBweXRob24gYXBwLnB5DQpyZW0gICAgbW9kdWxlIC0+IHB5dGhv
        echo biAtbSBwYWNrYWdlLm1vZHVsZQ0KcmVtICAgIHJ1bm5lciAtPiBweXRob24gLW0gcnVubmVyX21v
        echo ZHVsZSBbYXJncy4uLl0NCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNUX05BTUU9Q3J5cHRrZXkiDQpz
        echo ZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJFTlRSWV9NT0RFPWZpbGUiDQpzZXQgIkFQUF9FTlRS
        echo WT1zcmNcZmlsZV9lbmNyeXB0b3JfZW5oYW5jZWQucHkiDQpzZXQgIlJVTk5FUl9BUkdTPSINCg0K
        echo c2V0ICJQWT0lQ0QlXCVWRU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhlIg0KDQppZiBub3QgZXhp
        echo c3QgIiVQWSUiICgNCiAgICBlY2hvIFtFUlJPUl0gTG9jYWwgdmVudiBub3QgZm91bmQ6ICIlUFkl
        echo Ig0KICAgIGVjaG8uDQogICAgZWNobyBGaXggd2l0aDoNCiAgICBlY2hvICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNobyAgICIlVkVOVl9ESVIlXFNjcmlwdHNccHl0aG9uLmV4
        echo ZSIgLW0gcGlwIGluc3RhbGwgLS11cGdyYWRlIHBpcA0KICAgIGVjaG8gICAiJVZFTlZfRElSJVxT
        echo Y3JpcHRzXHB5dGhvbi5leGUiIC1tIHBpcCBpbnN0YWxsIC1yIHJlcXVpcmVtZW50cy50eHQNCiAg
        echo ICBlY2hvLg0KICAgIHBhdXNlDQogICAgZXhpdCAvYiAxDQopDQoNCmlmIC9JICIlRU5UUllfTU9E
        echo RSUiPT0iZmlsZSIgaWYgbm90IGV4aXN0ICIlQVBQX0VOVFJZJSIgKA0KICAgIGVjaG8gW0VSUk9S
        echo XSBFbnRyeSBmaWxlIG5vdCBmb3VuZDogIiVBUFBfRU5UUlklIg0KICAgIGVjaG8gRWRpdCBydW4u
        echo YmF0IG9yIHJ1biB3aXRoIHRoZSBjb3JyZWN0IGVudHJ5IGZpbGUuDQogICAgcGF1c2UNCiAgICBl
        echo eGl0IC9iIDENCikNCg0KdGl0bGUgIiVQUk9KRUNUX05BTUUlIC0gUlVOIg0KZWNobyA9PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVj
        echo aG8gIFJ1bm5pbmcgOiAlUFJPSkVDVF9OQU1FJQ0KZWNobyAgUHJvamVjdCA6ICVDRCUNCmVjaG8g
        echo IFB5dGhvbiAgOiAlUFklDQplY2hvICBNb2RlICAgIDogJUVOVFJZX01PREUlDQplY2hvICBFbnRy
        echo eSAgIDogJUFQUF9FTlRSWSUNCmlmIC9JICIlRU5UUllfTU9ERSUiPT0icnVubmVyIiBlY2hvICBB
        echo cmdzICAgIDogJVJVTk5FUl9BUkdTJQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8uDQoNCnNldCAiRVhJVENPREU9
        echo MCINCg0KaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJtb2R1bGUiICgNCiAgICAiJVBZJSIgLW0gJUFQ
        echo UF9FTlRSWSUgJSoNCikgZWxzZSBpZiAvSSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIgKA0KICAg
        echo IGlmIGRlZmluZWQgUlVOTkVSX0FSR1MgKA0KICAgICAgICAiJVBZJSIgLW0gJUFQUF9FTlRSWSUg
        echo IVJVTk5FUl9BUkdTISAlKg0KICAgICkgZWxzZSAoDQogICAgICAgICIlUFklIiAtbSAlQVBQX0VO
        echo VFJZJSAlKg0KICAgICkNCikgZWxzZSAoDQogICAgIiVQWSUiICIlQVBQX0VOVFJZJSIgJSoNCikN
        echo Cg0Kc2V0ICJFWElUQ09ERT0hRVJST1JMRVZFTCEiDQoNCmVjaG8uDQplY2hvID09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAg
        echo UHJvY2VzcyBleGl0ZWQgd2l0aCBjb2RlOiAhRVhJVENPREUhDQplY2hvID09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KcGF1c2UNCmV4
        echo aXQgL2IgIUVYSVRDT0RFIQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── pip.bat ─────────────────────────────────────────────────
set "OUTFILE=pip.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_pip_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QtbG9jYWwgcGlwIHdyYXBwZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxh
        echo dGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0
        echo ZWQgb246IDIwMjYtMDctMTEgMjI6MzQNCnJlbQ0KcmVtICBVc2FnZToNCnJlbSAgICBwaXAuYmF0
        echo IGluc3RhbGwgcmVxdWVzdHMNCnJlbSAgICBwaXAuYmF0IGluc3RhbGwgLXIgcmVxdWlyZW1lbnRz
        echo LnR4dA0KcmVtICAgIHBpcC5iYXQgZnJlZXplID4gcmVxdWlyZW1lbnRzLnR4dA0KcmVtICAgIHBp
        echo cC5iYXQgbGlzdA0KcmVtICAgIHBpcC5iYXQgdW5pbnN0YWxsIHJlcXVlc3RzDQpyZW0gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQoN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5
        echo dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2Nh
        echo bCB2ZW52IHdhcyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0K
        echo DQoiJVBZJSIgLW0gcGlwICUqDQpleGl0IC9iICVFUlJPUkxFVkVMJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── shell.bat ─────────────────────────────────────────────────
set "OUTFILE=shell.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_shell_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpjZCAvZCAiJX5kcDAiDQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCB2ZW52IHNo
        echo ZWxsDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRvciAoTGVv
        echo biBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2LTA3LTEx
        echo IDIyOjM0DQpyZW0NCnJlbSAgT3BlbnMgYW4gYWN0aXZhdGVkIENNRCBzZXNzaW9uIGZvciB0aGlz
        echo IHByb2plY3QuDQpyZW0gIFVzZSBvbmx5IHdoZW4geW91IG5lZWQgYW4gaW50ZXJhY3RpdmUgdmVu
        echo diBzZXNzaW9uLg0KcmVtICBFeGl0IHdpdGg6IGV4aXQNCnJlbSA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNU
        echo X05BTUU9Q3J5cHRrZXkiDQpzZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJBQ1RJVkFURT0lQ0Ql
        echo XCVWRU5WX0RJUiVcU2NyaXB0c1xhY3RpdmF0ZS5iYXQiDQoNCmlmIG5vdCBleGlzdCAiJUFDVElW
        echo QVRFJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2NhbCB2ZW52IHdhcyBub3QgZm91bmQ6DQogICAg
        echo ZWNobyAgICAgICAgICIlQUNUSVZBVEUlIg0KICAgIGVjaG8uDQogICAgZWNobyBDcmVhdGUgaXQg
        echo d2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZlbnYgIiVWRU5WX0RJUiUiDQogICAg
        echo ZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQp0aXRsZSAiJVBST0pFQ1RfTkFN
        echo RSUgLSBWRU5WIFNIRUxMIg0KY2FsbCAiJUFDVElWQVRFJSINCg0KZWNobyA9PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFBy
        echo b2plY3Qgc2hlbGwgYWN0aXZhdGVkDQplY2hvICBQcm9qZWN0OiAiJUNEJSINCmVjaG8gIFB5dGhv
        echo biA6DQp3aGVyZSBweXRob24NCmVjaG8gIFR5cGUgImV4aXQiIHRvIGxlYXZlIHRoaXMgc2hlbGwu
        echo DQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PQ0KZWNoby4NCmNtZCAvaw0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── sync.bat ─────────────────────────────────────────────────
set "OUTFILE=sync.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_sync_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIERlcGVu
        echo ZGVuY3kgU3luYyAocGlwKQ0KcmVtICBHZW5lcmF0ZWQgYnkgVmVudiBCYXRjaCBUZW1wbGF0ZSBH
        echo ZW5lcmF0b3IgKExlb24gUHJpZXN0IC8gN2gzdjAxZCkgdjMuNC4wDQpyZW0gIEdlbmVyYXRlZCBv
        echo bjogMjAyNi0wNy0xMSAyMjozNA0KcmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1DcnlwdGtl
        echo eSINCnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRz
        echo XHB5dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBM
        echo b2NhbCB2ZW52IG5vdCBmb3VuZDogIiVQWSUiDQogICAgZWNoby4NCiAgICBlY2hvIENyZWF0ZSBp
        echo dCB3aXRoOg0KICAgIGVjaG8gICBweXRob24gLW0gdmVudiAiJVZFTlZfRElSJSINCiAgICBwYXVz
        echo ZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQp0aXRsZSAiJVBST0pFQ1RfTkFNRSUgLSBTWU5DIg0KDQpl
        echo Y2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PQ0KZWNobyAgU3luY2luZzogJVBST0pFQ1RfTkFNRSUNCmVjaG8gIFB5dGhvbiA6ICVQ
        echo WSUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09DQplY2hvLg0KDQplY2hvIFsxLzNdIFVwZ3JhZGluZyBwaXAuLi4NCmVjaG8g
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09DQoiJVBZJSIgLW0gcGlwIGluc3RhbGwgLS11cGdyYWRlIHBpcA0KZWNoby4NCg0KaWYgZXhp
        echo c3QgInJlcXVpcmVtZW50cy50eHQiICgNCiAgICBlY2hvIFsyLzNdIEluc3RhbGxpbmcgZnJvbSBy
        echo ZXF1aXJlbWVudHMudHh0Li4uDQogICAgZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCiAgICAiJVBZJSIgLW0gcGlwIGluc3Rh
        echo bGwgLXIgcmVxdWlyZW1lbnRzLnR4dA0KICAgIGVjaG8uDQopIGVsc2UgKA0KICAgIGVjaG8gWzIv
        echo M10gU0tJUFBFRDogTm8gcmVxdWlyZW1lbnRzLnR4dCBmb3VuZC4NCiAgICBlY2hvICAgICAgIENy
        echo ZWF0ZSBvbmUgd2l0aDogcGlwLmJhdCBmcmVlemUgXj4gcmVxdWlyZW1lbnRzLnR4dA0KICAgIGVj
        echo aG8uDQopDQoNCmVjaG8gWzMvM10gRGVwZW5kZW5jeSBoZWFsdGggY2hlY2suLi4NCmVjaG8gPT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo DQoiJVBZJSIgLW0gcGlwIGNoZWNrDQplY2hvLg0KDQplY2hvID09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgU1lOQyBDT01Q
        echo TEVURQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT0NCnBhdXNlDQpleGl0IC9iIDANCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── doctor.bat ─────────────────────────────────────────────────
set "OUTFILE=doctor.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_doctor_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgRG9jdG9yDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRv
        echo ciAoTGVvbiBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2
        echo LTA3LTExIDIyOjM0DQpyZW0gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQoNCnNldCAiUFJPSkVDVF9OQU1FPUNyeXB0a2V5Ig0Kc2V0
        echo ICJWRU5WX0RJUj0udmVudiINCnNldCAiRU5UUllfTU9ERT1maWxlIg0Kc2V0ICJBUFBfRU5UUlk9
        echo c3JjXGZpbGVfZW5jcnlwdG9yX2VuaGFuY2VkLnB5Ig0Kc2V0ICJSVU5ORVJfQVJHUz0iDQpzZXQg
        echo IlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUiDQoNCmVjaG8gPT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hv
        echo ICBQUk9KRUNUIERPQ1RPUjogJVBST0pFQ1RfTkFNRSUNCmVjaG8gPT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBQcm9qZWN0
        echo IDogJUNEJQ0KZWNobyAgTW9kZSAgICA6ICVFTlRSWV9NT0RFJQ0KZWNobyAgRW50cnkgICA6ICVB
        echo UFBfRU5UUlklDQppZiAvSSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIgZWNobyAgQXJncyAgICA6
        echo ICVSVU5ORVJfQVJHUyUNCmVjaG8uDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8g
        echo W0ZBSUxdIHZlbnYgbm90IGZvdW5kIGF0OiAiJVBZJSINCiAgICBlY2hvLg0KICAgIGVjaG8gQ3Jl
        echo YXRlIGl0IHdpdGg6DQogICAgZWNobyAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9ESVIlIg0KICAg
        echo IHBhdXNlDQogICAgZXhpdCAvYiAxDQopDQoNCmVjaG8gW09LXSB2ZW52IGZvdW5kOiAiJVBZJSIN
        echo CmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBQeXRob24gRW52aXJvbm1lbnQNCmVjaG8gLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoi
        echo JVBZJSIgLWMgImltcG9ydCBzeXM7IHByaW50KCdFeGVjdXRhYmxlIDonLCBzeXMuZXhlY3V0YWJs
        echo ZSk7IHByaW50KCdWZXJzaW9uICAgIDonLCBzeXMudmVyc2lvbi5zcGxpdCgpWzBdKTsgcHJpbnQo
        echo J1ByZWZpeCAgICAgOicsIHN5cy5wcmVmaXgpIg0KZWNoby4NCg0KZWNobyAtLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVjaG8gIHBp
        echo cCB2ZXJzaW9uDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLQ0KIiVQWSUiIC1tIHBpcCAtLXZlcnNpb24NCmVjaG8uDQoNCmVj
        echo aG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tDQplY2hvICBJbnN0YWxsZWQgUGFja2FnZXMNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoiJVBZJSIgLW0gcGlw
        echo IGxpc3QNCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBEZXBlbmRlbmN5IEhlYWx0aA0KZWNobyAt
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0NCiIlUFklIiAtbSBwaXAgY2hlY2sNCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBFbnRyeSBQ
        echo b2ludCBDaGVjaw0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0NCmlmIC9JICIlRU5UUllfTU9ERSUiPT0iZmlsZSIgKA0KICAg
        echo IGlmIGV4aXN0ICIlQVBQX0VOVFJZJSIgKA0KICAgICAgICBlY2hvIFtPS10gRW50cnkgZmlsZSBm
        echo b3VuZDogIiVBUFBfRU5UUlklIg0KICAgICkgZWxzZSAoDQogICAgICAgIGVjaG8gW0ZBSUxdIEVu
        echo dHJ5IGZpbGUgTk9UIGZvdW5kOiAiJUFQUF9FTlRSWSUiDQogICAgKQ0KKSBlbHNlICgNCiAgICAi
        echo JVBZJSIgLWMgImltcG9ydCBpbXBvcnRsaWIudXRpbCwgc3lzOyBuYW1lPXInJUFQUF9FTlRSWSUn
        echo OyBzcGVjPWltcG9ydGxpYi51dGlsLmZpbmRfc3BlYyhuYW1lKTsgcHJpbnQoKCdbT0tdIE1vZHVs
        echo ZSBmb3VuZDogJyBpZiBzcGVjIGVsc2UgJ1tGQUlMXSBNb2R1bGUgTk9UIGZvdW5kOiAnKSArIG5h
        echo bWUpOyBzeXMuZXhpdCgwIGlmIHNwZWMgZWxzZSAxKSIgMj5udWwNCiAgICBpZiBlcnJvcmxldmVs
        echo IDEgZWNobyBbRkFJTF0gTW9kdWxlIGltcG9ydCB0ZXN0IGZhaWxlZC4NCiAgICBpZiAvSSAiJUVO
        echo VFJZX01PREUlIj09InJ1bm5lciIgZWNobyBbSU5GT10gUnVubmVyIGFyZ3M6ICIlUlVOTkVSX0FS
        echo R1MlIg0KKQ0KZWNoby4NCg0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVjaG8gIFByb2plY3QgRmlsZXMNCmVjaG8gLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo DQppZiBleGlzdCAidXYubG9jayIgICAgICAgICAgZWNobyBbT0tdICAgdXYubG9jayBmb3VuZA0K
        echo aWYgZXhpc3QgInB5cHJvamVjdC50b21sIiAgIGVjaG8gW09LXSAgIHB5cHJvamVjdC50b21sIGZv
        echo dW5kDQppZiBleGlzdCAicmVxdWlyZW1lbnRzLnR4dCIgZWNobyBbT0tdICAgcmVxdWlyZW1lbnRz
        echo LnR4dCBmb3VuZA0KaWYgbm90IGV4aXN0ICJyZXF1aXJlbWVudHMudHh0IiBlY2hvIFtXQVJOXSBy
        echo ZXF1aXJlbWVudHMudHh0IG1pc3NpbmcNCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBQeVF0NiBX
        echo ZWJFbmdpbmUgQ2hlY2sNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoiJVBZJSIgLWMgImZyb20gUHlRdDYgaW1wb3J0IFF0
        echo Q29yZTsgcHJpbnQoJ1B5UXQ6JywgUXRDb3JlLlBZUVRfVkVSU0lPTl9TVFIpOyBwcmludCgnUXQg
        echo IDonLCBRdENvcmUuUVRfVkVSU0lPTl9TVFIpOyBmcm9tIFB5UXQ2LlF0V2ViRW5naW5lV2lkZ2V0
        echo cyBpbXBvcnQgUVdlYkVuZ2luZVZpZXc7IHByaW50KCdbT0tdIFdlYkVuZ2luZSBpbXBvcnRlZCBz
        echo dWNjZXNzZnVsbHkuJykiIDI+JjENCmlmIGVycm9ybGV2ZWwgMSAoDQogICAgZWNobyBbRkFJTF0g
        echo UHlRdDYgV2ViRW5naW5lIGNoZWNrIGZhaWxlZC4NCiAgICBlY2hvICAgICAgICBSdW4gbWFudWFs
        echo bHkgZm9yIGZ1bGwgdHJhY2ViYWNrOg0KICAgIGVjaG8gICAgICAgICIlUFklIiAtYyAiZnJvbSBQ
        echo eVF0Ni5RdFdlYkVuZ2luZVdpZGdldHMgaW1wb3J0IFFXZWJFbmdpbmVWaWV3Ig0KKSBlbHNlICgN
        echo CiAgICBlY2hvIFtPS10gUHlRdDYgV2ViRW5naW5lIGlzIGF2YWlsYWJsZS4NCikNCmVjaG8uDQoN
        echo CmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09DQplY2hvICBET0NUT1IgQ09NUExFVEUNCmVjaG8gPT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhpdCAv
        echo YiAwDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── test.bat ─────────────────────────────────────────────────
set "OUTFILE=test.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_test_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgdGVzdCBydW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxhdGUgR2Vu
        echo ZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0ZWQgb246
        echo IDIwMjYtMDctMTEgMjI6MzQNCnJlbQ0KcmVtICBSdW5zIHB5dGVzdCB2aWEgdGhlIHByb2plY3Qt
        echo bG9jYWwgdmVudiBQeXRob24uDQpyZW0NCnJlbSAgVXNhZ2U6DQpyZW0gICAgdGVzdC5iYXQgICAg
        echo ICAgICAgICAgICAgICAgICAgICAocnVuIGFsbCB0ZXN0cykNCnJlbSAgICB0ZXN0LmJhdCB0ZXN0
        echo cy90ZXN0X2NvcmUucHkgICAgIChydW4gYSBzcGVjaWZpYyBmaWxlKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC1rIG1hcHBlciAgICAgICAgICAgICAgKGZpbHRlciBieSBuYW1lKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC12IC0tdGI9c2hvcnQgICAgICAgICAgKHZlcmJvc2Ugd2l0aCBzaG9ydCB0cmFjZWJhY2tzKQ0K
        echo cmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1DcnlwdGtleSINCnNldCAiVkVOVl9ESVI9LnZl
        echo bnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUiDQoNCmlmIG5v
        echo dCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2NhbCB2ZW52IHdhcyBub3QgZm91
        echo bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8uDQogICAgcGF1c2UNCiAgICBl
        echo eGl0IC9iIDENCikNCg0KdGl0bGUgIiVQUk9KRUNUX05BTUUlIC0gVEVTVCINCmVjaG8gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpl
        echo Y2hvICBUZXN0aW5nOiAiJVBST0pFQ1RfTkFNRSUiDQplY2hvICBQeXRob24gOiAiJVBZJSINCmVj
        echo aG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09DQplY2hvLg0KIiVQWSUiIC1tIHB5dGVzdCAtdiAlKg0Kc2V0ICJFWElUQ09ERT0lRVJS
        echo T1JMRVZFTCUiDQoNCmVjaG8uDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KaWYgIiVFWElUQ09ERSUiPT0iMCIgKA0KICAg
        echo IGVjaG8gIFRFU1RTIFBBU1NFRA0KKSBlbHNlICgNCiAgICBlY2hvICBURVNUUyBGQUlMRUQgIF4o
        echo ZXhpdCBjb2RlOiAlRVhJVENPREUlXikNCikNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhpdCAvYiAlRVhJ
        echo VENPREUlDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo.
echo  Companion scripts written (existing files were NOT overwritten).
echo  Add them to .gitignore to keep your repo tidy.
echo.
echo  Next steps:
echo    run.bat    - Launch %PROJECT_NAME%
echo    sync.bat   - Reinstall / update dependencies
echo    shell.bat  - Open activated venv shell
echo    doctor.bat - Environment health check
echo    pip.bat    - Project-local pip wrapper
echo    test.bat   - Run pytest suite
echo ============================================================
pause
exit /b 0
